# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Hatena
version:      0.01
version_from: lib/Template/Plugin/Hatena.pm
installdirs:  site
requires:
    Template:                      2.08
    Test::More:                    0.32
    Text::Hatena:                  0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
